- name: "[DEMO SAMPLE] NOI - Ansible runbook"
  hosts: all
  tasks: 
    - name: resolve disk error 
      shell: |
        echo "log message"
        echo "Service" {{ SERVICE }}
        /tmp/test-ansible.sh {{ SERVICE }}
